agent:
  id: "windows-agent-001"
  name: "Windows Security Agent"
  version: "1.0.0"
  collector_interval: 30
  log_level: "info"

database:
  host: "ep-super-pine-a1glsjev-pooler.ap-southeast-1.aws.neon.tech"
  port: 5432
  user: "neondb_owner"
  password: "npg_vsHuI17fBYML"
  dbname: "neondb"
  sslmode: "require"

server:
  port: 8080
